"""add_is_partner_to_brands

Revision ID: 4b3f0b055e23
Revises: 59a39f5dd861
Create Date: 2026-04-14 12:05:25.868787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3f0b055e23'
down_revision: Union[str, None] = '59a39f5dd861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('is_partner', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'is_partner')
    # ### end Alembic commands ###
